# VM identity
vm_name: cloud-vm02
vm_memory: 2048
vm_vcpus: 2
vm_disk_size: 20G
vm_os_variant: ubuntu22.04

# Libvirt
libvirt_pool: amine-pool
libvirt_pool_dir: /home/admin/amine
libvirt_network: amine-net

# Cloud image
base_image_url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
base_image_name: jammy-base.qcow2

# SSH
ssh_public_key: "{{ lookup('file', '~/.ssh/ocp4upi.pub') }}"